from __future__ import annotations

from .diagnostics import InternalCompilerError
from .nodes import (
    BinaryExpression,
    BooleanLiteral,
    CallExpression,
    Expression,
    IdentifierExpression,
    IfExpression,
    IntegerLiteral,
    LetStatement,
    Program,
    ReturnStatement,
)

GENERATED_PREFIX = "ocl."
ENTRY_LABEL = f"{GENERATED_PREFIX}entry"


def _escape_llvm_string(value: str) -> str:
    """Encode UTF-8 bytes for an LLVM quoted string."""
    return "".join(
        chr(byte) if 0x20 <= byte <= 0x7E and byte not in (0x22, 0x5C) else f"\\{byte:02X}"
        for byte in value.encode("utf-8")
    )


def _llvm_type(type_name: str) -> str:
    try:
        return {"bool": "i1", "i32": "i32"}[type_name]
    except KeyError as error:
        raise InternalCompilerError(f"unsupported type reached codegen: {type_name}") from error


def generate_llvm_ir(program: Program, source_name: str = "input.ocl") -> str:
    """Lower a program that has already passed `semantic.analyze`."""
    lines = [
        "; Generated by oclc 0.4",
        f'source_filename = "{_escape_llvm_string(source_name)}"',
        "",
    ]
    functions = {function.name: function for function in program.functions}
    for function in program.functions:
        if not function.body or not isinstance(function.body[-1], ReturnStatement):
            raise InternalCompilerError(
                f"function '{function.name}' reached codegen without a final return statement; "
                "semantic analysis must run before lowering"
            )
        parameters = ", ".join(f"{_llvm_type(parameter.type_name)} %{parameter.name}" for parameter in function.parameters)
        body_lines: list[str] = []
        temporary = [0]
        block_number = [0]
        current_block = [ENTRY_LABEL]
        values = {parameter.name: (f"%{parameter.name}", parameter.type_name) for parameter in function.parameters}
        for statement in function.body[:-1]:
            if not isinstance(statement, LetStatement):
                raise InternalCompilerError(f"unsupported statement reached codegen: {type(statement).__name__}")
            values[statement.name] = _lower_expression(
                statement.initializer, body_lines, temporary, block_number, current_block, values, functions
            )
        value, value_type = _lower_expression(
            function.body[-1].expression, body_lines, temporary, block_number, current_block, values, functions
        )
        lines.extend((
            f"define {_llvm_type(function.return_type)} @{function.name}({parameters}) {{",
            f"{ENTRY_LABEL}:",
            *body_lines,
            f"  ret {_llvm_type(value_type)} {value}",
            "}",
            "",
        ))
    return "\n".join(lines)


def _operands(expression: Expression) -> tuple[Expression, ...]:
    if isinstance(expression, BinaryExpression):
        return (expression.left, expression.right)
    if isinstance(expression, CallExpression):
        return expression.arguments
    return ()


def _new_temporary(temporary: list[int]) -> str:
    result = f"%{temporary[0]}"
    temporary[0] += 1
    return result


def _new_if_labels(block_number: list[int]) -> tuple[str, str, str]:
    number = block_number[0]
    block_number[0] += 1
    return (
        f"{GENERATED_PREFIX}if.then.{number}",
        f"{GENERATED_PREFIX}if.else.{number}",
        f"{GENERATED_PREFIX}if.merge.{number}",
    )


def _lower_expression(
    expression: Expression,
    lines: list[str],
    temporary: list[int],
    block_number: list[int],
    current_block: list[str],
    values: dict[str, tuple[str, str]],
    functions: dict,
) -> tuple[str, str]:
    """Lower one expression without recursing over its AST.

    The state machine also handles nested `if` expressions. Each branch records
    the block where its value was produced so the merge phi remains correct when
    a branch itself contains control flow.
    """
    results: dict[int, tuple[str, str]] = {}
    pending: list[tuple[Expression, str, object]] = [(expression, "visit", None)]
    while pending:
        node, stage, data = pending.pop()
        if stage == "visit":
            if isinstance(node, BooleanLiteral):
                results[id(node)] = ("1" if node.value else "0", "bool")
                continue
            if isinstance(node, IntegerLiteral):
                results[id(node)] = (str(node.value), "i32")
                continue
            if isinstance(node, IdentifierExpression):
                try:
                    results[id(node)] = values[node.name]
                except KeyError as error:
                    raise InternalCompilerError(f"unresolved identifier reached codegen: {node.name}") from error
                continue
            if isinstance(node, IfExpression):
                pending.append((node, "condition", None))
                pending.append((node.condition, "visit", None))
                continue
            if not isinstance(node, (BinaryExpression, CallExpression)):
                raise InternalCompilerError(f"unsupported expression reached codegen: {type(node).__name__}")
            pending.append((node, "ready", None))
            pending.extend((operand, "visit", None) for operand in reversed(_operands(node)))
            continue

        if stage == "condition":
            condition, condition_type = results[id(node.condition)]
            if condition_type != "bool":
                raise InternalCompilerError("non-bool if condition reached codegen")
            then_label, else_label, merge_label = _new_if_labels(block_number)
            lines.append(f"  br i1 {condition}, label %{then_label}, label %{else_label}")
            lines.append(f"{then_label}:")
            current_block[0] = then_label
            pending.append((node, "then", (else_label, merge_label)))
            pending.append((node.then_expression, "visit", None))
            continue

        if stage == "then":
            else_label, merge_label = data
            then_value = results[id(node.then_expression)]
            then_block = current_block[0]
            lines.append(f"  br label %{merge_label}")
            lines.append(f"{else_label}:")
            current_block[0] = else_label
            pending.append((node, "else", (merge_label, then_value, then_block)))
            pending.append((node.else_expression, "visit", None))
            continue

        if stage == "else":
            merge_label, then_value, then_block = data
            else_value = results[id(node.else_expression)]
            else_block = current_block[0]
            if then_value[1] != else_value[1]:
                raise InternalCompilerError("mismatched if branch types reached codegen")
            lines.append(f"  br label %{merge_label}")
            lines.append(f"{merge_label}:")
            current_block[0] = merge_label
            result = _new_temporary(temporary)
            llvm_type = _llvm_type(then_value[1])
            lines.append(
                f"  {result} = phi {llvm_type} [{then_value[0]}, %{then_block}], "
                f"[{else_value[0]}, %{else_block}]"
            )
            results[id(node)] = (result, then_value[1])
            continue

        if stage != "ready":
            raise InternalCompilerError(f"unsupported codegen state: {stage}")

        result = _new_temporary(temporary)
        if isinstance(node, BinaryExpression):
            left, left_type = results[id(node.left)]
            right, right_type = results[id(node.right)]
            arithmetic = {"+": "add", "-": "sub", "*": "mul"}
            comparison = {"<": "slt", "<=": "sle", ">": "sgt", ">=": "sge", "==": "eq", "!=": "ne"}
            if node.operator in arithmetic:
                lines.append(f"  {result} = {arithmetic[node.operator]} i32 {left}, {right}")
                result_type = "i32"
            elif node.operator in comparison:
                operand_type = _llvm_type(left_type)
                if left_type != right_type:
                    raise InternalCompilerError("mismatched comparison operands reached codegen")
                lines.append(f"  {result} = icmp {comparison[node.operator]} {operand_type} {left}, {right}")
                result_type = "bool"
            else:
                raise InternalCompilerError(f"unsupported binary operator reached codegen: {node.operator}")
        elif isinstance(node, CallExpression):
            try:
                callee = functions[node.callee]
            except KeyError as error:
                raise InternalCompilerError(f"unresolved function reached codegen: {node.callee}") from error
            rendered = ", ".join(
                f"{_llvm_type(results[id(argument)][1])} {results[id(argument)][0]}" for argument in node.arguments
            )
            lines.append(f"  {result} = call {_llvm_type(callee.return_type)} @{node.callee}({rendered})")
            result_type = callee.return_type
        else:
            raise InternalCompilerError(f"unsupported expression reached codegen: {type(node).__name__}")
        results[id(node)] = (result, result_type)
    return results[id(expression)]
