from __future__ import annotations

from .diagnostics import InternalCompilerError
from .parser import FRAMES_PER_BLOCK_LEVEL, MAX_BLOCK_DEPTH
from .stack import reserved
from .nodes import (
    BinaryExpression,
    AssignmentStatement,
    ArrayLiteral,
    BlockStatement,
    BreakStatement,
    BooleanLiteral,
    CallExpression,
    ContinueStatement,
    Expression,
    IdentifierExpression,
    IfExpression,
    EnumVariantExpression,
    MatchExpression,
    FieldAssignmentStatement,
    FieldExpression,
    IndexAssignmentStatement,
    IndexExpression,
    IntegerLiteral,
    LetStatement,
    Program,
    ReturnStatement,
    UnaryExpression,
    StructLiteral,
    VarStatement,
    WhileStatement,
)
from .types import EnumType, StructType

GENERATED_PREFIX = "ocl."
ENTRY_LABEL = f"{GENERATED_PREFIX}entry"


def _escape_llvm_string(value: str) -> str:
    """Encode UTF-8 bytes for an LLVM quoted string."""
    return "".join(
        chr(byte) if 0x20 <= byte <= 0x7E and byte not in (0x22, 0x5C) else f"\\{byte:02X}"
        for byte in value.encode("utf-8")
    )


def _llvm_type(type_name: str) -> str:
    if type_name.startswith("[") and type_name.endswith("]") and ";" in type_name:
        element, length = type_name[1:-1].split(";", 1)
        return f"[{int(length.strip())} x {_llvm_type(element.strip())}]"
    if isinstance(type_name, StructType):
        return f"%ocl.struct.{type_name.name}"
    if isinstance(type_name, EnumType):
        return "i32"
    try:
        return {"bool": "i1", "i32": "i32"}[type_name]
    except KeyError as error:
        raise InternalCompilerError(f"unsupported type reached codegen: {type_name}") from error


def generate_llvm_ir(program: Program, source_name: str = "input.ocl") -> str:
    """Lower a program that has already passed `semantic.analyze`.

    `_lower_statements` recurses once per block level, so it reserves stack for
    the depth the parser admits, exactly as semantic analysis does.
    """
    with reserved(MAX_BLOCK_DEPTH * FRAMES_PER_BLOCK_LEVEL):
        return _generate(program, source_name)


def _generate(program: Program, source_name: str) -> str:
    lines = [
        "; Generated by oclc 0.9",
        f'source_filename = "{_escape_llvm_string(source_name)}"',
        "",
    ]
    structures = {structure.name: structure for structure in program.structures}
    enumerations = {enumeration.name: enumeration for enumeration in program.enumerations}
    for structure in program.structures:
        fields = ", ".join(_llvm_type(field.type_name) for field in structure.fields)
        lines.append(f"%ocl.struct.{structure.name} = type {{ {fields} }}")
    if program.structures:
        lines.append("")
    lines.extend(("declare void @llvm.trap()", ""))
    functions = {function.name: function for function in program.functions}
    for function in program.functions:
        parameters = ", ".join(f"{_llvm_type(parameter.type_name)} %{parameter.name}" for parameter in function.parameters)
        body_lines: list[str] = []
        temporary = [0]
        block_number = [0]
        current_block = [ENTRY_LABEL]
        values = {parameter.name: (f"%{parameter.name}", parameter.type_name) for parameter in function.parameters}
        mutable = _mutable_bindings(function.body)
        for name, type_name in mutable:
            body_lines.append(f"  %ocl.var.{name} = alloca {_llvm_type(type_name)}")
        terminated = _lower_statements(function.body, body_lines, temporary, block_number, current_block, values, functions, structures, enumerations)
        if not terminated:
            raise InternalCompilerError(f"function '{function.name}' reached codegen without returning")
        lines.extend((
            f"define {_llvm_type(function.return_type)} @{function.name}({parameters}) {{",
            f"{ENTRY_LABEL}:",
            *body_lines,
            "}",
            "",
        ))
    return "\n".join(lines)


def _mutable_bindings(statements):
    found = []
    pending = list(reversed(statements))
    while pending:
        statement = pending.pop()
        if isinstance(statement, VarStatement) or (
            isinstance(statement, LetStatement) and (statement.type_name.startswith("[") or isinstance(statement.type_name, StructType))
        ):
            found.append((statement.name, statement.type_name))
        elif isinstance(statement, BlockStatement):
            pending.extend(reversed(statement.statements))
        elif isinstance(statement, WhileStatement):
            pending.extend(reversed(statement.body.statements))
    return found


def _new_labels(block_number, stem, count):
    number = block_number[0]
    block_number[0] += 1
    return tuple(f"{GENERATED_PREFIX}{stem}.{part}.{number}" for part in count)


def _lower_statements(statements, lines, temporary, block_number, current_block, values, functions, structures, enumerations, loop_targets=()):
    for statement in statements:
        if isinstance(statement, (LetStatement, VarStatement)):
            if isinstance(statement.type_name, StructType):
                pointer = f"%ocl.var.{statement.name}"
                if not isinstance(statement.initializer, StructLiteral):
                    raise InternalCompilerError("non-literal structure initializer reached codegen")
                structure = structures[statement.type_name.name]
                indexes = {field.name: index for index, field in enumerate(structure.fields)}
                types = {field.name: field.type_name for field in structure.fields}
                for field in statement.initializer.fields:
                    value, actual_type = _lower_expression(field.expression, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
                    field_pointer = _new_temporary(temporary)
                    lines.append(
                        f"  {field_pointer} = getelementptr inbounds {_llvm_type(statement.type_name)}, "
                        f"ptr {pointer}, i32 0, i32 {indexes[field.name]}"
                    )
                    lines.append(f"  store {_llvm_type(types[field.name])} {value}, ptr {field_pointer}")
                values[statement.name] = (pointer, statement.type_name, True)
                continue
            if statement.type_name.startswith("["):
                pointer = f"%ocl.var.{statement.name}"
                if not isinstance(statement.initializer, ArrayLiteral):
                    raise InternalCompilerError("non-literal array initializer reached codegen")
                element_type, length = _array_parts(statement.type_name)
                for index, element in enumerate(statement.initializer.elements):
                    value, actual_type = _lower_expression(element, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
                    element_pointer = _new_temporary(temporary)
                    lines.append(
                        f"  {element_pointer} = getelementptr inbounds {_llvm_type(statement.type_name)}, "
                        f"ptr {pointer}, i32 0, i32 {index}"
                    )
                    lines.append(f"  store {_llvm_type(element_type)} {value}, ptr {element_pointer}")
                values[statement.name] = (pointer, statement.type_name, True)
                continue
            value, type_name = _lower_expression(statement.initializer, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            if isinstance(statement, VarStatement):
                pointer = f"%ocl.var.{statement.name}"
                lines.append(f"  store {_llvm_type(type_name)} {value}, ptr {pointer}")
                values[statement.name] = (pointer, type_name, True)
            else:
                values[statement.name] = (value, type_name)
        elif isinstance(statement, AssignmentStatement):
            value, type_name = _lower_expression(statement.expression, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            pointer = values[statement.name][0]
            lines.append(f"  store {_llvm_type(type_name)} {value}, ptr {pointer}")
        elif isinstance(statement, IndexAssignmentStatement):
            binding = values[statement.name]
            index, index_type = _lower_expression(statement.index, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            pointer, element_type = _guarded_element_pointer(
                binding[0], binding[1], index, lines, temporary, block_number, current_block
            )
            value, value_type = _lower_expression(statement.expression, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            lines.append(f"  store {_llvm_type(element_type)} {value}, ptr {pointer}")
        elif isinstance(statement, FieldAssignmentStatement):
            binding = values[statement.name]
            structure = structures[binding[1].name]
            index = next(index for index, field in enumerate(structure.fields) if field.name == statement.field)
            field_type = structure.fields[index].type_name
            value, value_type = _lower_expression(statement.expression, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            pointer = _new_temporary(temporary)
            lines.append(
                f"  {pointer} = getelementptr inbounds {_llvm_type(binding[1])}, ptr {binding[0]}, i32 0, i32 {index}"
            )
            lines.append(f"  store {_llvm_type(field_type)} {value}, ptr {pointer}")
        elif isinstance(statement, ReturnStatement):
            value, type_name = _lower_expression(statement.expression, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            lines.append(f"  ret {_llvm_type(type_name)} {value}")
            return "return"
        elif isinstance(statement, BreakStatement):
            lines.append(f"  br label %{loop_targets[-1][1]}")
            return "break"
        elif isinstance(statement, ContinueStatement):
            lines.append(f"  br label %{loop_targets[-1][0]}")
            return "continue"
        elif isinstance(statement, BlockStatement):
            flow = _lower_statements(statement.statements, lines, temporary, block_number, current_block, dict(values), functions, structures, enumerations, loop_targets)
            if flow:
                return flow
        elif isinstance(statement, WhileStatement):
            condition_label, body_label, exit_label = _new_labels(block_number, "while", ("condition", "body", "exit"))
            lines.append(f"  br label %{condition_label}")
            lines.append(f"{condition_label}:")
            current_block[0] = condition_label
            condition, condition_type = _lower_expression(statement.condition, lines, temporary, block_number, current_block, values, functions, structures, enumerations)
            lines.append(f"  br i1 {condition}, label %{body_label}, label %{exit_label}")
            lines.append(f"{body_label}:")
            current_block[0] = body_label
            body_flow = _lower_statements(statement.body.statements, lines, temporary, block_number, current_block, dict(values), functions, structures, enumerations, loop_targets + ((condition_label, exit_label),))
            if not body_flow:
                lines.append(f"  br label %{condition_label}")
            lines.append(f"{exit_label}:")
            current_block[0] = exit_label
        else:
            raise InternalCompilerError(f"unsupported statement reached codegen: {type(statement).__name__}")
    return None


def _operands(expression: Expression) -> tuple[Expression, ...]:
    if isinstance(expression, BinaryExpression):
        return (expression.left, expression.right)
    if isinstance(expression, CallExpression):
        return expression.arguments
    if isinstance(expression, UnaryExpression):
        return (expression.operand,)
    if isinstance(expression, IndexExpression):
        return (expression.base, expression.index)
    if isinstance(expression, FieldExpression):
        return (expression.base,)
    if isinstance(expression, MatchExpression):
        return (expression.scrutinee, *(arm.expression for arm in expression.arms))
    return ()


def _new_temporary(temporary: list[int]) -> str:
    result = f"%{temporary[0]}"
    temporary[0] += 1
    return result


def _new_if_labels(block_number: list[int]) -> tuple[str, str, str]:
    number = block_number[0]
    block_number[0] += 1
    return (
        f"{GENERATED_PREFIX}if.then.{number}",
        f"{GENERATED_PREFIX}if.else.{number}",
        f"{GENERATED_PREFIX}if.merge.{number}",
    )


def _array_parts(type_name: str) -> tuple[str, int]:
    try:
        element, length = type_name[1:-1].split(";", 1)
        return element.strip(), int(length.strip())
    except (ValueError, AttributeError) as error:
        raise InternalCompilerError(f"invalid array type reached codegen: {type_name}") from error


def _guarded_element_pointer(array_pointer, array_type, index, lines, temporary, block_number, current_block):
    element_type, length = _array_parts(array_type)
    valid = _new_temporary(temporary)
    pointer = _new_temporary(temporary)
    trap_label, safe_label = _new_labels(block_number, "bounds", ("trap", "safe"))
    lines.extend((
        f"  {valid} = icmp ult i32 {index}, {length}",
        f"  br i1 {valid}, label %{safe_label}, label %{trap_label}",
        f"{trap_label}:",
        "  call void @llvm.trap()",
        "  unreachable",
        f"{safe_label}:",
        f"  {pointer} = getelementptr inbounds {_llvm_type(array_type)}, ptr {array_pointer}, i32 0, i32 {index}",
    ))
    current_block[0] = safe_label
    return pointer, element_type


def _lower_expression(
    expression: Expression,
    lines: list[str],
    temporary: list[int],
    block_number: list[int],
    current_block: list[str],
    values: dict[str, tuple[str, str]],
    functions: dict,
    structures: dict,
    enumerations: dict,
) -> tuple[str, str]:
    """Lower one expression without recursing over its AST.

    The state machine also handles nested `if` expressions. Each branch records
    the block where its value was produced so the merge phi remains correct when
    a branch itself contains control flow.
    """
    results: dict[int, tuple[str, str]] = {}
    pending: list[tuple[Expression, str, object]] = [(expression, "visit", None)]
    while pending:
        node, stage, data = pending.pop()
        if stage == "visit":
            if isinstance(node, BooleanLiteral):
                results[id(node)] = ("1" if node.value else "0", "bool")
                continue
            if isinstance(node, IntegerLiteral):
                results[id(node)] = (str(node.value), "i32")
                continue
            if isinstance(node, EnumVariantExpression):
                enumeration = enumerations[node.enum_name]
                ordinal = next(index for index, variant in enumerate(enumeration.variants) if variant.name == node.variant)
                results[id(node)] = (str(ordinal), EnumType(node.enum_name))
                continue
            if isinstance(node, IdentifierExpression):
                try:
                    binding = values[node.name]
                except KeyError as error:
                    raise InternalCompilerError(f"unresolved identifier reached codegen: {node.name}") from error
                if len(binding) == 3 and not binding[1].startswith("[") and not isinstance(binding[1], StructType):
                    result = _new_temporary(temporary)
                    lines.append(f"  {result} = load {_llvm_type(binding[1])}, ptr {binding[0]}")
                    results[id(node)] = (result, binding[1])
                else:
                    results[id(node)] = binding[:2]
                continue
            if isinstance(node, IfExpression):
                pending.append((node, "condition", None))
                pending.append((node.condition, "visit", None))
                continue
            if isinstance(node, MatchExpression):
                pending.append((node, "match-dispatch", None))
                pending.append((node.scrutinee, "visit", None))
                continue
            if isinstance(node, BinaryExpression) and node.operator in ("&&", "||"):
                pending.append((node, "logical-left", None))
                pending.append((node.left, "visit", None))
                continue
            if isinstance(node, ArrayLiteral):
                raise InternalCompilerError("array literal reached codegen outside a local initializer")
            if isinstance(node, StructLiteral):
                raise InternalCompilerError("structure literal reached codegen outside a local initializer")
            if not isinstance(node, (BinaryExpression, CallExpression, UnaryExpression, IndexExpression, FieldExpression)):
                raise InternalCompilerError(f"unsupported expression reached codegen: {type(node).__name__}")
            pending.append((node, "ready", None))
            pending.extend((operand, "visit", None) for operand in reversed(_operands(node)))
            continue

        if stage == "match-dispatch":
            scrutinee, scrutinee_type = results[id(node.scrutinee)]
            enumeration = enumerations[str(scrutinee_type)]
            arm_labels = _new_labels(block_number, "match", tuple(f"arm{index}" for index in range(len(node.arms))))
            merge_label, invalid_label = _new_labels(block_number, "match", ("merge", "invalid"))
            ordinals = {variant.name: index for index, variant in enumerate(enumeration.variants)}
            lines.append(f"  switch i32 {scrutinee}, label %{invalid_label} [")
            for arm, label in zip(node.arms, arm_labels):
                lines.append(f"    i32 {ordinals[arm.variant]}, label %{label}")
            lines.append("  ]")
            lines.extend((f"{invalid_label}:", "  call void @llvm.trap()", "  unreachable", f"{arm_labels[0]}:"))
            current_block[0] = arm_labels[0]
            pending.append((node, "match-arm", (0, arm_labels, merge_label, [])))
            pending.append((node.arms[0].expression, "visit", None))
            continue

        if stage == "match-arm":
            index, arm_labels, merge_label, completed = data
            value = results[id(node.arms[index].expression)]
            completed.append((value, current_block[0]))
            lines.append(f"  br label %{merge_label}")
            next_index = index + 1
            if next_index < len(node.arms):
                lines.append(f"{arm_labels[next_index]}:")
                current_block[0] = arm_labels[next_index]
                pending.append((node, "match-arm", (next_index, arm_labels, merge_label, completed)))
                pending.append((node.arms[next_index].expression, "visit", None))
                continue
            result_type = completed[0][0][1]
            if any(item[0][1] != result_type for item in completed):
                raise InternalCompilerError("mismatched match arm types reached codegen")
            lines.append(f"{merge_label}:")
            current_block[0] = merge_label
            result = _new_temporary(temporary)
            incoming = ", ".join(f"[{item[0][0]}, %{item[1]}]" for item in completed)
            lines.append(f"  {result} = phi {_llvm_type(result_type)} {incoming}")
            results[id(node)] = (result, result_type)
            continue

        if stage == "logical-left":
            left, left_type = results[id(node.left)]
            rhs_label, merge_label = _new_labels(block_number, "logic", ("rhs", "merge"))
            left_block = current_block[0]
            if node.operator == "&&":
                lines.append(f"  br i1 {left}, label %{rhs_label}, label %{merge_label}")
                shortcut = "0"
            else:
                lines.append(f"  br i1 {left}, label %{merge_label}, label %{rhs_label}")
                shortcut = "1"
            lines.append(f"{rhs_label}:")
            current_block[0] = rhs_label
            pending.append((node, "logical-right", (merge_label, left_block, shortcut)))
            pending.append((node.right, "visit", None))
            continue

        if stage == "logical-right":
            merge_label, left_block, shortcut = data
            right, right_type = results[id(node.right)]
            right_block = current_block[0]
            lines.append(f"  br label %{merge_label}")
            lines.append(f"{merge_label}:")
            current_block[0] = merge_label
            result = _new_temporary(temporary)
            lines.append(f"  {result} = phi i1 [{shortcut}, %{left_block}], [{right}, %{right_block}]")
            results[id(node)] = (result, "bool")
            continue

        if stage == "condition":
            condition, condition_type = results[id(node.condition)]
            if condition_type != "bool":
                raise InternalCompilerError("non-bool if condition reached codegen")
            then_label, else_label, merge_label = _new_if_labels(block_number)
            lines.append(f"  br i1 {condition}, label %{then_label}, label %{else_label}")
            lines.append(f"{then_label}:")
            current_block[0] = then_label
            pending.append((node, "then", (else_label, merge_label)))
            pending.append((node.then_expression, "visit", None))
            continue

        if stage == "then":
            else_label, merge_label = data
            then_value = results[id(node.then_expression)]
            then_block = current_block[0]
            lines.append(f"  br label %{merge_label}")
            lines.append(f"{else_label}:")
            current_block[0] = else_label
            pending.append((node, "else", (merge_label, then_value, then_block)))
            pending.append((node.else_expression, "visit", None))
            continue

        if stage == "else":
            merge_label, then_value, then_block = data
            else_value = results[id(node.else_expression)]
            else_block = current_block[0]
            if then_value[1] != else_value[1]:
                raise InternalCompilerError("mismatched if branch types reached codegen")
            lines.append(f"  br label %{merge_label}")
            lines.append(f"{merge_label}:")
            current_block[0] = merge_label
            result = _new_temporary(temporary)
            llvm_type = _llvm_type(then_value[1])
            lines.append(
                f"  {result} = phi {llvm_type} [{then_value[0]}, %{then_block}], "
                f"[{else_value[0]}, %{else_block}]"
            )
            results[id(node)] = (result, then_value[1])
            continue

        if stage != "ready":
            raise InternalCompilerError(f"unsupported codegen state: {stage}")

        result = _new_temporary(temporary)
        if isinstance(node, BinaryExpression):
            left, left_type = results[id(node.left)]
            right, right_type = results[id(node.right)]
            arithmetic = {"+": "add", "-": "sub", "*": "mul"}
            comparison = {"<": "slt", "<=": "sle", ">": "sgt", ">=": "sge", "==": "eq", "!=": "ne"}
            if node.operator in arithmetic:
                lines.append(f"  {result} = {arithmetic[node.operator]} i32 {left}, {right}")
                result_type = "i32"
            elif node.operator in ("/", "%"):
                zero = result
                minimum = _new_temporary(temporary)
                negative_one = _new_temporary(temporary)
                overflow = _new_temporary(temporary)
                invalid = _new_temporary(temporary)
                result = _new_temporary(temporary)
                trap_label, safe_label = _new_labels(block_number, "division", ("trap", "safe"))
                lines.extend((
                    f"  {zero} = icmp eq i32 {right}, 0",
                    f"  {minimum} = icmp eq i32 {left}, -2147483648",
                    f"  {negative_one} = icmp eq i32 {right}, -1",
                    f"  {overflow} = and i1 {minimum}, {negative_one}",
                    f"  {invalid} = or i1 {zero}, {overflow}",
                    f"  br i1 {invalid}, label %{trap_label}, label %{safe_label}",
                    f"{trap_label}:",
                    "  call void @llvm.trap()",
                    "  unreachable",
                    f"{safe_label}:",
                    f"  {result} = {'sdiv' if node.operator == '/' else 'srem'} i32 {left}, {right}",
                ))
                current_block[0] = safe_label
                result_type = "i32"
            elif node.operator in comparison:
                operand_type = _llvm_type(left_type)
                if left_type != right_type:
                    raise InternalCompilerError("mismatched comparison operands reached codegen")
                lines.append(f"  {result} = icmp {comparison[node.operator]} {operand_type} {left}, {right}")
                result_type = "bool"
            else:
                raise InternalCompilerError(f"unsupported binary operator reached codegen: {node.operator}")
        elif isinstance(node, CallExpression):
            try:
                callee = functions[node.callee]
            except KeyError as error:
                raise InternalCompilerError(f"unresolved function reached codegen: {node.callee}") from error
            rendered = ", ".join(
                f"{_llvm_type(results[id(argument)][1])} {results[id(argument)][0]}" for argument in node.arguments
            )
            lines.append(f"  {result} = call {_llvm_type(callee.return_type)} @{node.callee}({rendered})")
            result_type = callee.return_type
        elif isinstance(node, UnaryExpression):
            operand, operand_type = results[id(node.operand)]
            if node.operator == "!":
                lines.append(f"  {result} = xor i1 {operand}, true")
                result_type = "bool"
            else:
                lines.append(f"  {result} = sub i32 0, {operand}")
                result_type = "i32"
        elif isinstance(node, IndexExpression):
            array_pointer, array_type = results[id(node.base)]
            index, index_type = results[id(node.index)]
            pointer, result_type = _guarded_element_pointer(
                array_pointer, array_type, index, lines, temporary, block_number, current_block
            )
            result = _new_temporary(temporary)
            lines.append(f"  {result} = load {_llvm_type(result_type)}, ptr {pointer}")
        elif isinstance(node, FieldExpression):
            base_pointer, base_type = results[id(node.base)]
            structure = structures[base_type.name]
            index = next(index for index, field in enumerate(structure.fields) if field.name == node.field)
            result_type = structure.fields[index].type_name
            pointer = _new_temporary(temporary)
            lines.append(
                f"  {pointer} = getelementptr inbounds {_llvm_type(base_type)}, ptr {base_pointer}, i32 0, i32 {index}"
            )
            result = _new_temporary(temporary)
            lines.append(f"  {result} = load {_llvm_type(result_type)}, ptr {pointer}")
        else:
            raise InternalCompilerError(f"unsupported expression reached codegen: {type(node).__name__}")
        results[id(node)] = (result, result_type)
    return results[id(expression)]
