from .nodes import BinaryExpression, CallExpression, Expression, IdentifierExpression, IntegerLiteral, Program
from .diagnostics import InternalCompilerError


def _escape_llvm_string(value: str) -> str:
    """Encode UTF-8 bytes for an LLVM quoted string."""
    return "".join(
        chr(byte) if 0x20 <= byte <= 0x7E and byte not in (0x22, 0x5C) else f"\\{byte:02X}"
        for byte in value.encode("utf-8")
    )


def generate_llvm_ir(program: Program, source_name: str = "input.ocl") -> str:
    """Lower a program that has already passed `semantic.analyze`."""
    lines = [
        "; Generated by oclc 0.2",
        f'source_filename = "{_escape_llvm_string(source_name)}"',
        "",
    ]
    for function in program.functions:
        if len(function.body) != 1:
            raise InternalCompilerError(
                f"function '{function.name}' reached codegen with {len(function.body)} statements; "
                "semantic analysis must run before lowering"
            )
        parameters = ", ".join(f"i32 %{parameter.name}" for parameter in function.parameters)
        body_lines: list[str] = []
        temporary = [0]
        value = _lower_expression(function.body[0].expression, body_lines, temporary)
        lines.extend((f"define i32 @{function.name}({parameters}) {{", "entry:", *body_lines, f"  ret i32 {value}", "}", ""))
    return "\n".join(lines)


def _lower_expression(expression: Expression, lines: list[str], temporary: list[int]) -> str:
    if isinstance(expression, IntegerLiteral):
        return str(expression.value)
    if isinstance(expression, IdentifierExpression):
        return f"%{expression.name}"
    if isinstance(expression, BinaryExpression):
        left = _lower_expression(expression.left, lines, temporary)
        right = _lower_expression(expression.right, lines, temporary)
        result = f"%{temporary[0]}"
        temporary[0] += 1
        lines.append(f"  {result} = add i32 {left}, {right}")
        return result
    if isinstance(expression, CallExpression):
        arguments = [_lower_expression(argument, lines, temporary) for argument in expression.arguments]
        result = f"%{temporary[0]}"
        temporary[0] += 1
        rendered = ", ".join(f"i32 {argument}" for argument in arguments)
        lines.append(f"  {result} = call i32 @{expression.callee}({rendered})")
        return result
    raise InternalCompilerError(f"unsupported expression reached codegen: {type(expression).__name__}")
